#pragma once

#include <QObject>
#include <QJsonObject>
#include <QJsonArray>
#include <QVariantMap>
#include <QHash>
#include <QSet>

#include "JsonUtils.h"
#include "views/Module.h"
#include "views/MainTemplate.h"
#include "views/AppLinks.h"
#include "views/AppRoles.h"
#include <jsoncons/json.hpp>
#include <jsoncons_ext/csv/csv.hpp>
#include <json/json.h>
#include "base/CsvUtil.h"
#include "sqliteone.hpp"


class WrapUpload;
/**
 * @brief Handles the iteration and API dispatch for bulk item and category data.
 * * This class processes the large JSON payload generated by LibArchiveExtractor,
 * mapping array data for each item into individual QVariantMaps and routing
 * them to the appropriate Network API functions (newitem, updateitem, newcategory).
 */
class DataUploader : public Wt::WObject
{


public:
    DataUploader();
    ~DataUploader();

    /**
     * @brief Iterates over the JSON payload and calls the appropriate API functions.
     * * Categories are created only if the associated item has actiondue="new" and 
     * the category has not been uploaded yet in the current batch.
     * * @param payload The QJsonObject containing "categories_data" and "extracted_data".
     */

    void uploadExtractedItems(const QJsonObject& payload);
    void propagateUpload();
    void doUpload(const QJsonObject&);
    static DataUploader *getInstance();
    static DataUploader *instance;
    // Placeholders for the actual DataNet API functions (replace with calls to your DataNet instance)
    void newcategoryuploader(QVariantMap info);
    void newitemuploader(QVariantMap info);
    void updateitemuploader(QVariantMap info);

    std::wstring myurldue(AppLinks links);
    std::wstring myroledue(AppRoles roles);
    void uservalidity(QVariantMap info);
    void categoryexistence(QVariantMap info);
    void itemexistence(QVariantMap info);
    void loginuser(QVariantMap info);
    void registeruser(QVariantMap info);
    void retrievepassword(QVariantMap info);
    void newcategory(QVariantMap info);
    void newitem(QVariantMap info);
    void queryitems(QVariantMap info);
    void userbyid(QVariantMap info);
    void userdata(QVariantMap info);
    void usersubscription(QVariantMap info);
    void updateitem(QVariantMap info);
    void deleteitem(QVariantMap info);
    void deletecategory(QVariantMap info);
    void newrequest(QVariantMap info);
    void updaterequest(QVariantMap info);
    void deleterequest(QVariantMap info);
    void queryrequest(QVariantMap info);
    void deleteitemcategory(QVariantMap info);
    void fetchspecific(QVariantMap info);
    void logout(QVariantMap info);
    void passwordupdate(QVariantMap info);
    void phonenumberupdate(QVariantMap info);
    void getallitems();
    void getuseritems(QString user);
    void starttimer1();
    void starttimer2();
    void starttimer3();
    void starttimer4();
    Wt::Signal<std::string>& myrestdata() { return myrestdata_; }
    Wt::Signal<std::string>& myrestnetworkError() { return networkErrormyrest_; }
    Wt::Signal<std::string>& myrestserverError() { return serverErrormyrest_; }
    Wt::Signal<bool>& timer1() { return mytimer1_; }
    Wt::Signal<bool>& timer2() { return mytimer2_; }
    Wt::Signal<bool>& timer3() { return mytimer3_; }
    Wt::Signal<std::string> myrestdata_;
    Wt::Signal<std::string> networkErrormyrest_;
    Wt::Signal<std::string> serverErrormyrest_;
    Wt::Signal<bool> mytimer1_;
    Wt::Signal<bool> mytimer2_;
    Wt::Signal<bool> mytimer3_;
    Wt::Signal<std::string>& usernameresourceready() { return usernameresource_; }
    std::string fromIstream(std::istream &stream);
    std::unique_ptr<Wt::Http::Client> client_;
    void requestDone(Wt::AsioWrapper::error_code ec, const Wt::Http::Message &msg);
    void requestDoneWithin(Wt::AsioWrapper::error_code ec, const Wt::Http::Message &msg);
    void mybodyDataReceived(std::string bodydata);
    std::string combimsg ="";
    bool start = true;
    std::shared_ptr<MyJsonTools> mypayload;
    std::shared_ptr<eric::JsonUtils> myjsonutils;
    Wt::Signal<std::string> usernameresource_;



private:
    std::unique_ptr<WrapUpload>  qtSender_, qtReceiver_;


};
