#pragma once

#include <QObject>
#include <QJsonObject>
#include <QJsonArray>
#include <QVariantMap>
#include <QHash>
#include <QSet>

// Forward declaration of DataNet is recommended if DataUploader is separate.
// If DataUploader is a part of DataNet, this is not needed.
class DataNet;
class MapperSoftware;
class MyJsonTools;

// Forward declare Wt::Http::Client
namespace Wt {
namespace Http {
class Client; // Correct forward declaration
}
}

// Forward declare eric::JsonUtils
namespace eric {
class JsonUtils; // Correct forward declaration
}





/**
 * @brief Handles the iteration and API dispatch for bulk item and category data.
 * * This class processes the large JSON payload generated by LibArchiveExtractor,
 * mapping array data for each item into individual QVariantMaps and routing
 * them to the appropriate DataNet API functions (newitem, updateitem, newcategory).
 */
class DataUploader : public QObject
{
    Q_OBJECT

public:
   // explicit DataUploader(QObject *parent = nullptr,);
    explicit DataUploader( QObject *parent = nullptr,DataNet* dataNetInstance = nullptr,MapperSoftware *mappersoftware=nullptr,Wt::Http::Client *client=nullptr,std::shared_ptr<MyJsonTools> mypayload_=nullptr ,std::shared_ptr<eric::JsonUtils> myjsonutils_=nullptr); // Example with dependency injection

    /**
     * @brief Iterates over the JSON payload and calls the appropriate API functions.
     * * Categories are created only if the associated item has actiondue="new" and 
     * the category has not been uploaded yet in the current batch.
     * * @param payload The QJsonObject containing "categories_data" and "extracted_data".
     */
    void uploadExtractedItems(const QJsonObject& payload);

private:
    // Placeholders for the actual DataNet API functions (replace with calls to your DataNet instance)
    void newcategory(QVariantMap info);
    void newitem(QVariantMap info);
    void updateitem(QVariantMap info);

    std::shared_ptr<DataNet> m_dataNet; // Example dependency member
    Wt::Http::Client *client_;
    std::shared_ptr<MyJsonTools> mypayload;
    std::shared_ptr<eric::JsonUtils> myjsonutils;
    Wt::Signal<std::string> usernameresource_;
    MapperSoftware *mappersoftware_;

};
