#ifndef _QX_DIGITALBLOOMORDERS_PRECOMPILED_HEADER_H_
#define _QX_DIGITALBLOOMORDERS_PRECOMPILED_HEADER_H_

#include <QxOrm.h>
#include <export.h>
#include <regex>
#include <fstream>
#include <streambuf>
#include <iostream>
#include <sstream>
#include <boost/log/trivial.hpp>
#include <string>
#include <memory>
#include <algorithm>
#include <cstdlib>
#include <boost/thread.hpp>
#include <stdlib.h>
#include <ciso646>
#include <functional>
#include <cassert>
#include <iomanip>
#include <cstring>
#include <cstdio>
#include <math.h>
#include <fstream>
#include <stdlib.h>
#include <boost/tokenizer.hpp>
#include <ctype.h>
#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <boost/algorithm/string/split.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/filesystem/exception.hpp>
#include <boost/algorithm/string.hpp>
#include <sys/stat.h>
#include <stdexcept>
#include <boost/array.hpp>
#include <list>
#include <map>
#include <string>
#include <signal.h>
#include <string.h>
#include <QObject>
#include <QTimer>
#include <QRandomGenerator>
#include <QRandomGenerator64>
#include <QElapsedTimer>
#include <QCryptographicHash>
#include <QSettings>
#include <QJsonDocument>
#include <QJsonArray>
#include <QJsonObject>
#include <QJsonValue>
#include <QJsonParseError>
#include <QFile>
#include <QUuid>
#include <QTimer>
#include <QRegularExpression>
#include "qjsonwebtoken.h"
#include <csignal>
#include <cstring>
#include <string>
#include <vector>
#include <chrono>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <iostream>
#include <iomanip>
#include <ctime>
#include <time.h>
#include <cmath>
#include <QDateTime>
#include <QTimeZone>
#include <QDebug>
#include <QByteArray>
#include <QList>
#include "Parser/Parser.h"
#include "JsonUtils.h"
#include <hpdf.h>
#include <boost/algorithm/string/classification.hpp>
#include <boost/algorithm/string/split.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/algorithm/string.hpp>
#include <sstream>
#include <cryptopp/cryptlib.h>
#include <cryptopp/secblock.h>
#include <cryptopp/chacha.h>
#include <cryptopp/osrng.h>
#include <cryptopp/files.h>
#include <cryptopp/hex.h>
#include "ericsettings/SettingsManagerEric.h"
#include <QFileInfo>
#include <QUrl>
#include <QString>
#include <QDir>
#include <QStandardPaths>
#include <QMultiMap>
#include <QxPrecompiled.h>
#include <QxRestApi/QxRestApi.h>
#include <QxOrm_Impl.h>
#include <QxDao/IxPersistable.h>
#include <QxDao/IxPersistableCollection.h>
#include <QxDao/IxPersistableList.h>
#include <QxDao/QxSqlError.h>
#include <QxDao/QxSqlQuery.h>
#include <QxDao/QxSqlDatabase.h>
#include <QxDao/QxSqlSaveMode.h>
#include <QxFactory/QxFactoryX.h>
#include <QxRegister/IxClass.h>
#include <QxRegister/QxClassX.h>
#include <QxValidator/QxInvalidValueX.h>
#ifndef _QX_NO_JSON
#include <QxSerialize/QJson/QxSerializeQJson_QxSqlQuery.h>
#include <QxSerialize/QJson/QxSerializeQJson_QStringList.h>
#include <QxSerialize/QJson/QxSerializeQJson_IxSqlElement.h>
#include <QxSerialize/QJson/QxSerializeQJson_QxCollection.h>
#include <QxSerialize/QJson/QxSerializeQJson_QxInvalidValue.h>
#include <QxSerialize/QJson/QxSerializeQJson_QxInvalidValueX.h>
#endif // _QX_NO_JSON
#include <QxCommon/QxException.h>
#include <QxCommon/QxExceptionCode.h>
#include <QxMemLeak/mem_leak.h>
#include <QLoggingCategory>
#include <QCommandLineOption>
#include <QCommandLineParser>
#include <QCoreApplication>
#include <QMetaType>
#include "Parser/Parser.h"
#include <Wt/Http/Client.h>
#include <Wt/WServer.h>
#include <Wt/WResource.h>
#include <Wt/Http/Request.h>
#include <Wt/Http/Response.h>
#include <Wt/WStringStream.h>
#include <Wt/WTemplate.h>
#include <Wt/WText.h>
#include <Wt/WContainerWidget.h>
#include <Wt/WLoadingIndicator.h>
#include <Wt/WStandardItemModel.h>
#include <Wt/WAbstractItemModel.h>
#include <Wt/WSortFilterProxyModel.h>
#include <Wt/WApplication.h>
#include <Wt/WEnvironment.h>
#include <Wt/WStandardItem.h>
#include <Wt/WAbstractTableModel.h>
#include <Wt/WStringListModel.h>
#include <Wt/WLink.h>
#include <Wt/WTextEdit.h>
#include <Wt/WEvent.h>
#include <Wt/WProgressBar.h>
#include <Wt/WTimer.h>
#include <Wt/WMessageBox.h>
#include <Wt/WFormModel.h>
#include <Wt/WIntValidator.h>
#include <Wt/WValidator.h>
#include <Wt/WIconPair.h>
#include <Wt/WPopupMenu.h>
#include <Wt/WToolBar.h>
#include <Wt/WAnchor.h>
#include <Wt/WObject.h>
#include <Wt/WButtonGroup.h>
#include <Wt/WRadioButton.h>
#include <Wt/WCheckBox.h>
#include <Wt/WSpinBox.h>
#include <Wt/WSplitButton.h>
#include <Wt/WDoubleSpinBox.h>
#include <Wt/WFileUpload.h>
#include <Wt/WFileDropWidget.h>
#include <Wt/Auth/PasswordService.h>
#include <Wt/Auth/PasswordVerifier.h>
#include <Wt/WPanel.h>
#include <Wt/WDialog.h>
#include <Wt/WRegExpValidator.h>
#include <Wt/WDate.h>
#include <Wt/WDateValidator.h>
#include <Wt/WLabel.h>
#include <Wt/WDateEdit.h>
#include <Wt/WValidator.h>
#include <Wt/WComboBox.h>
#include <Wt/WSelectionBox.h>
#include <Wt/WFormModel.h>
#include <Wt/WLengthValidator.h>
#include <Wt/WModelIndex.h>
#include <Wt/WTemplateFormView.h>
#include <Wt/WAbstractItemModel.h>
#include <Wt/WAbstractItemView.h>
#include <Wt/WSuggestionPopup.h>
#include <Wt/WTimeEdit.h>
#include <Wt/WLabel.h>
#include <Wt/WTextArea.h>
#include <Wt/WDateTime.h>
#include <Wt/WMenuItem.h>
#include <Wt/WTabWidget.h>
#include <Wt/WInPlaceEdit.h>
#include <Wt/WNavigationBar.h>
#include <Wt/WBorder.h>
#include <Wt/WGroupBox.h>
#include <Wt/WCircleArea.h>
#include <Wt/WPolygonArea.h>
#include <Wt/WRectArea.h>
#include <Wt/WAny.h>
#include <Wt/WString.h>
#include <Wt/WStringUtil.h>
#include <Wt/WBreak.h>
#include <Wt/WSlider.h>
#include <Wt/WFitLayout.h>
#include <Wt/WBootstrap2Theme.h>
#include <Wt/WBootstrap3Theme.h>
#include <Wt/WBootstrap5Theme.h>
#include <Wt/WLayout.h>
#include <Wt/WNavigationBar.h>
#include <Wt/WCompositeWidget.h>
#include <Wt/WStackedWidget.h>
#include <Wt/WCssTheme.h>
#include <Wt/WCssDecorationStyle.h>
#include <Wt/WComboBox.h>
#include <Wt/WPushButton.h>
#include <Wt/WDefaultLoadingIndicator.h>
#include <Wt/WOverlayLoadingIndicator.h>
#include <Wt/WLineEdit.h>
#include <Wt/WHBoxLayout.h>
#include <Wt/WVBoxLayout.h>
#include <Wt/Utils.h>
#include <Wt/WDateTime.h>
#include <Wt/WTimer.h>
#include <Wt/Dbo/Dbo.h>
#include <Wt/Dbo/Json.h>
#include <Wt/Dbo/FixedSqlConnectionPool.h>
#include <Wt/Json/Parser.h>
#include <Wt/Json/Serializer.h>
#include <Wt/Json/Object.h>
#include <Wt/Json/Array.h>
#include <Wt/Json/Value.h>
#include <Wt/WLogger.h>
#include <Wt/WLeafletMap.h>
#include <Wt/WFlashObject.h>
#include <Wt/WVideo.h>
#include <QTemporaryFile>
#include <QProcess>
#include <boost/iostreams/filtering_stream.hpp>
#include <boost/iostreams/filter/lzma.hpp>
#include <web/Configuration.h>
#include <web/WebController.h>
#include <QxHttpServer/QxHttpServer.h>       // adjust include as needed
#include <QxHttpServer/QxHttpRequest.h>       // adjust include as needed
#include <QxService/QxConnect.h>             // adjust include as needed
#include <Wt/cpp17/filesystem.hpp>
#include <algorithm>











#endif // _QX_DIGITALBLOOMORDERS_PRECOMPILED_HEADER_H_
